<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Cucumber" time="4.398" tests="1" skipped="0" failures="1" errors="0">
<testcase classname="Room Validation" name="Validate Room by Room Number" time="4.248">
<failure type="java.lang.AssertionError">
<![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at stepdefinitions.db_stepdefinitions.UserDBStepDefs.verify_usernamelist_contains(UserDBStepDefs.java:31)
	at âœ½.verify usernamelist contains "75634221"(file:///C:/Users/can07/IdeaProjects/my-cucumber-project/./src/test/resources/features/db_features/room_db.feature:7)
]]>
</failure>
<system-out><![CDATA[
Given user connects to database.............................................passed
When get all "room_number" as a list from "room"............................passed
Then verify usernamelist contains "75634221"................................failed
And close the connection....................................................skipped
]]></system-out>
</testcase>
</testsuite>
